name: Upload files to S3

on:
  push:
    branches:
      - main

env:
  MY_AWS_REGION: "ap-northeast-1"
  AWS_ROLENAME: "s1mlog-prd-github-role"
  AWS_S3_BUCKET: "s1mlog-prd-static-web-hosting-bucket"
  SOURCE_DIR: "../../../front/,next"
  DEST_DIR: "./"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure AWS credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.AWS_ROLENAME}}
          aws-region: ${{env.MY_AWS_REGION}}
      - name: Copy files to S3
        run: |
          aws s3 sync ${{env.SOURCE_DIR}} s3://${{env.AWS_S3_BUCKET}}/${{env.DEST_DIR}}/ --exclude '.*git*'
